### ISSUE TITLE
bundleAssets should return a promise of builtResult

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-bundler#28]
currently `bundleAssets` is return a promise of an array of `inferredBundle` and `globbedBundle`. this is not helpful.

`inferredBundle` and `globbedBundle` should add infos to the buitResult and return it.

https://github.com/stealjs/steal-bundler/blob/master/lib/main.js#L25
can look like this:
```js
return Promise.all(promises).then(function () {
		return buildResult;
	});
```

with that change i can chain the `bundleAssets` with `serviceworker` during build, because `steal-serviceworker` need the `builtResult` to work
in `steal-tools` multibuild the code can look like this:
```
					var p = Promise.resolve(builtResult);

					if(options.bundleAssets){
						var bundleAssets = require("steal-bundler");
						p = p.then(function(b) {
							return bundleAssets(builtResult, options.bundleAssets)
						});
					}

					if(options.serviceWorker){
						var precache = require("steal-serviceworker");
						p = p.then(function (b) {
							return precache(builtResult, options.serviceWorker)
						});
					}
```

cc @matthewp

**Comment by matthewp** [comment]
+1
