### ISSUE TITLE
Support for hashes?

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-bundler#8]
Do you plan to add?

**Comment by justinbmeyer** [comment]
What do you mean by hashes?

**Comment by whitecolor** [comment]
When you append asset names with hashes for cache busting.

**Comment by justinbmeyer** [comment]
I think there is the cache buster extension already.

**Comment by whitecolor** [comment]
Ok, then bundler lacks docs.

**Comment by matthewp** [comment]
https://github.com/stealjs/cache-bust
